### PR TITLE
Search Preview

### PR DESCRIPTION
**Pull request by pteasima**
make it possible to navigate from MoviesView to MovieSearchView programmatically, use that in MovieSearchView preview, various fixes to make that work

### CODE REVIEW

**Comment by pteasima** [comment]
@tillkruss in its current form, this only uses MoviesView for the preview in MovieSearchView.swift . So it doesn't have the tabs from ContentView. Do you think those are needed.

Code should make it clear how we're driving the navigation from `@State` in `MoviesView`. I can of course hoist that `@State` to ContentView and make it available to `MoviesView` as a Binding, but at that point we should consider:
- putting the whole `NavigationStack` for MoviesView tab into `ContentView`, since its associated path state also lives there
OR
- driving the navigation from some global `Router` object, so that we can more easily control it from anywhere and not have to worry about where the `@State` is. Im personally not fan of such Router objects for my strict MVC codebases, but others commonly do this and it might be fine for your architecture.

The proposed changes might be excessive if we're only doing it for a preview, so I felt the need to ask.

**Comment by pteasima** [comment]
I had a few issues while implementing this, took longer than expected:
- there was an extra NavigationStack in `MovieSearchView`, which made the navigation freak out. I removed it.
- there's a lot of state synchronization around instances, I was struggling to get a non-nil radarrInstance. I think there's potential for simplication as mentioned in some of my comments. Would be happy to talk about that.

Lmk if any of this should be acted on before we merge this.

PR still needs cleanup, thus its a draft for now.

**Comment by pteasima** [comment]
@tillkruss can you confirm that the preview is fine as is (without the tabbar, for reasons mentioned above)? I'd like to finalize and merge this so I can rebase other branches against these changes.

**Comment by tillkruss** [comment]
> @tillkruss can you confirm that the preview is fine as is (without the tabbar, for reasons mentioned above)? I'd like to finalize and merge this so I can rebase other branches against these changes.

Yeah, sure.

**Pull request merged**
